version: "3.8"

services:
  mc:
    ports:
      - "25566:25565"
      - "25575:25575"
    volumes:
      - "mcbig:/data"
    environment:
      EULA: "TRUE"
      # TYPE: FORGE
      # FORGEVERSION: "47.2.0"
      VERSION: "1.20.1"
      MEMORY: "8G"
      RCON_PASSWORD: minecraft
    image: itzg/minecraft-server
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: mc
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
  bot:
    # image: naari3/minecraft-command-bot
    build:
      context: .
    environment:
      RCON_HOST: mc
      RCON_PASSWORD: minecraft
      DISCORD_BOT_TOKEN: your_token
      DISCORD_BOT_PREFIX: \
      MINECRAFT_LOG_PATH: /data/logs/latest.log
      MINECRAFT_LOG_CHANNEL_ID: "974809758655721542"
    volumes:
      - "mcbig:/data"

volumes:
  mcbig:
  rcon:
