name: build-image

on:
  release:
    types:
      - created

jobs:
  build:
    uses: naari3/workflows/.github/workflows/build-multiarch-images-ghcr.yaml@main
    with:
      tag_name: ${{ github.event.release.tag_name }}
      target_arch: linux/amd64,linux/arm64
    secrets:
      github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
